name: Get RunPod GPU Locations with API Key and Save to Repo

on:
  workflow_dispatch: # Enable manual trigger since scheduled trigger is removed

jobs:
  get-gpu-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script to get GPU locations
      env:
        RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      run: python /full_runpod_gpus.py > full_gpu_db.txt # Changed script path and output file name

    - name: Commit and Push GPU locations to repository
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add full_gpu_db.txt # Changed file name to commit
        git commit -m "Update RunPod GPU locations" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
