name: Get GCP GPU Locations with API Key and Save to Repo

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows manual triggering from GitHub Actions tab

jobs:
  get-gpu-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-compute

    - name: Run Python script to get GPU locations
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: python get_gcp_gpus.py > gcp_gpu_locations.txt

    - name: Commit and Push GPU locations to repository
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add gcp_gpu_locations.txt
        git commit -m "Update GCP GPU locations" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
