name: Get RunPod GPU Locations with API Key and Save to Repo

on:
  # workflow_dispatch: # Comment out or remove this line to disable manual trigger
  schedule:
    # Runs every hour
    # For cron syntax:
    # minute (0-59)
    # hour (0-23)
    # day of month (1-31)
    # month (1-12)
    # day of week (0-6, where 0 and 6 are Sunday and Saturday)
    #
    # '0 * * * *' means:
    # 0: at minute 0
    # *: every hour
    # *: every day of the month
    # *: every month
    # *: every day of the week
    - cron: '0 * * * *'

jobs:
  get-gpu-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script to get GPU locations
      env:
        RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      run: python get_runpod_gpus.py > runpod_gpu_locations.txt

    - name: Commit and Push GPU locations to repository
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add runpod_gpu_locations.txt
        git commit -m "Update RunPod GPU locations" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
