name: RUNPOD GPU Availability

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Debug API Key
        run: echo "First 5 chars of key: ${RUNPOD_API_KEY:0:5}"
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}

      - name: Fetch GPU availability from RunPod
        run: |
          python fetch_runpod_gpu_availability.py
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}

      - name: Commit and push GPU data
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add runpod_gpu_locations.json
          git commit -m "Update RUNPOD GPU availability" || echo "No changes"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
