name: Get RunPod GPU Locations and Save to Repo # שם ה-workflow ב-GitHub Actions

on:
  workflow_dispatch: # מאפשר הפעלה ידנית של ה-workflow מהממשק של GitHub

jobs:
  get-gpu-data:
    runs-on: ubuntu-latest # מערכת ההפעלה שבה ירוץ ה-job
    permissions:
      contents: write # *** חובה: הרשאת כתיבה לריפוזיטורי כדי לבצע commit ו-push ***

    steps:
    - name: Checkout repository # שלב 1: משיכת קוד הריפוזיטורי
      uses: actions/checkout@v4

    - name: Set up Python # שלב 2: הגדרת סביבת Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies # שלב 3: התקנת ספריות Python נדרשות (כמו requests)
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script to get GPU locations # שלב 4: הרצת סקריפט הפייתון ושמירת הפלט לקובץ זמני
      run: python get_runpod_gpus.py > runpod_gpu_locations.txt

    - name: Commit and Push GPU locations to repository # שלב 5: ביצוע commit ו-push של הקובץ המעודכן לריפוזיטורי
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add runpod_gpu_locations.txt
        git commit -m "Update RunPod GPU locations" || echo "No changes to commit"
        git push
