name: Get RunPod GPU Locations

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  get-gpu-data:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests # Install the 'requests' library to make HTTP requests

    - name: Run Python script to get GPU locations
      run: python get_runpod_gpus.py > runpod_gpu_locations.txt
      # This command executes your Python script and redirects its output
      # to a file named 'runpod_gpu_locations.txt'.

    - name: Upload GPU locations artifact
      uses: actions/upload-artifact@v4
      with:
        name: runpod-gpu-locations
        path: runpod_gpu_locations.txt
        # This step uploads the generated file as an artifact, so you can download it
        # from the GitHub Actions run summary.
